// Utils.h

#ifndef __UTILS__
#define __UTILS__
#include <stdio.h>
#include <string>
#include <SDL.h>
#include "SDL2Berzerk.h"



enum USEREVENTS { GAME_OVER = SDL_USEREVENT, PLAYER_WALL_COLLISION, PLAYER_EXIT_MAZE, PLAYER_ROBOT_COLLISION, PLAYER_ROBOTEXPLODE_COLLISION, PLAYER_BULLET_COLLISION, PLAYER_OTTO_COLLISION, PLAYER_ELECTROCUTED, ROBOT_WALL_COLLISION, ROBOT_BULLET_COLLISION, ROBOT_OTTO_COLLISION, ROBOT_ROBOTEXPLODE_COLLISIONS, ROBOT_KILL, PLAYER_BULLET_FIRE, ROBOT_BULLET_FIRE, BULLET_KILL, ROBOT_ACTIVE, OTTO_SPAWN, OTTO_ACTIVE, OTTO_BULLET, OTTO_ROBOT, OTTO_PLAYER };

extern void UserEvent(USEREVENTS, void *, void *);

//Box collision detector
extern bool checkCollision(SDL_Rect, SDL_Rect);

extern bool saveScreenShotBMP(std::string, SDL_Window *, SDL_Renderer *);

#endif

